apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-deployment
  labels:
    app: mlflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      containers:
        - name: mlflow
          image: harbor.kosmos.idcp.inovex.io/analyse-platform-kosmos/mlflow:latest
          ports:
          - containerPort: 5000
            hostPort: 5000
            protocol: TCP
      imagePullSecrets:
      - name: regcrd

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mlflow
  name: mlflow-service
spec:
  selector:
    app: mlflow
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000