
flwr_server_address: "[::1]:50052"
socketio_address: "0.0.0.0:6000"
mlflow_server_address: "http://localhost:5000" #This can either be a local directory or a remote mlflow-server address
mlflow_experiment_name: "default_config"
num_clients: 1
tags:
  experiment_name: "default_config"

n_federated_train_epoch: 10
usecase:
  name: "BearingUseCase"
  params:
    test_bearings: ["Bearing1_3", "Bearing1_4"]
  broadcast:
    test: "Test"

# usecase:
#   name: "TurbofanUseCase"
#   params:
#     file_path: "../test.csv"  # TODO has to be adapted
#   broadcast:
#     sequence_length: 100
#     loss: "RootMeanSquaredError"
#     remaining_sensors: ['setting_1', 'setting_2', 'sensor_02', 'sensor_03', 'sensor_04', 'sensor_07', 'sensor_08', 'sensor_09', 'sensor_11', 'sensor_12', 'sensor_13', 'sensor_14', 'sensor_15', 'sensor_17','sensor_20', 'sensor_21']
#     min_max_norm_columns: ['sensor_17', 'setting_2']
DEBUG: False
